### ISSUE TITLE
Triggernometry v1.1.6.9 issues

### ISSUE THREAD

**Issue by RenYuanXue** [gynryiie/Auto-Crafter#2]
Need to replace end of line symbol **$** to **\|[^|]*$** because of the update.

So the 6th and 90th line needs a change.

**Comment by gynryiie** [comment]
I'm still using Triggernometry v1.1.6.4, and the issue doesn't seem to exist there, but looks like this has also been fixed in v1.1.6.9b (from the Triggernometry discord).
https://discord.com/channels/374517624228544512/599935468578144276/1064108381582929951

I'll be closing the thread since this is a Triggernometry issue, and not the trigger.

**Comment by gynryiie** [comment]
Thanks for the report, fixed instead with `(?:\|[^\|]*)?$` for backwards compatibility.
